"""Property-based tests for input validators.

Tests email and string validation functions with various inputs.
RULE: Maximum 100 lines per file.
"""

import pytest
from hypothesis import given, strategies as st

from python_input_validation.validators import (
    validate_email_format,
    validate_string_length,
)
from .strategies.email import email_strategy


class TestEmailValidation:
    """Property-based tests for email validation."""

    @given(email=email_strategy())
    def test_valid_emails_pass_validation(self, email):
        """Emails generated by email_strategy should pass validation."""
        assert validate_email_format(email), f"Valid email {email} failed validation"

    @given(text=st.text(max_size=50))
    def test_invalid_emails_fail_validation(self, text):
        """Non-email text should mostly fail validation."""
        # Filter out accidentally valid emails
        if '@' not in text or '.' not in text.split('@')[-1]:
            assert not validate_email_format(text)

    def test_empty_string_fails(self):
        """Empty string should fail email validation."""
        assert not validate_email_format("")

    def test_missing_at_symbol_fails(self):
        """Email without @ should fail."""
        assert not validate_email_format("userexample.com")

    def test_missing_domain_fails(self):
        """Email without domain should fail."""
        assert not validate_email_format("user@")

    def test_missing_tld_fails(self):
        """Email without TLD should fail."""
        assert not validate_email_format("user@example")

    def test_valid_email_formats_pass(self):
        """Known valid email formats should pass."""
        valid_emails = [
            "user@example.com",
            "test.user@example.co.uk",
            "admin+tag@test.org",
            "user123@domain123.com",
        ]
        for email in valid_emails:
            assert validate_email_format(email), f"{email} should be valid"


class TestStringLengthValidation:
    """Property-based tests for string length validation."""

    @given(text=st.text(min_size=10, max_size=20))
    def test_text_within_range_passes(self, text):
        """Text within min/max range should pass."""
        assert validate_string_length(text, min_length=5, max_length=25)

    @given(text=st.text(min_size=0, max_size=5))
    def test_text_below_minimum_fails(self, text):
        """Text below minimum length should fail."""
        if len(text) < 10:
            assert not validate_string_length(text, min_length=10)

    @given(text=st.text(min_size=30, max_size=50))
    def test_text_above_maximum_fails(self, text):
        """Text above maximum length should fail."""
        if len(text) > 20:
            assert not validate_string_length(text, max_length=20)

    @given(text=st.text(max_size=100))
    def test_no_constraints_always_passes(self, text):
        """Text with no constraints should always pass."""
        assert validate_string_length(text)

    def test_exact_minimum_length_passes(self):
        """Text exactly at minimum length should pass."""
        assert validate_string_length("12345", min_length=5)

    def test_exact_maximum_length_passes(self):
        """Text exactly at maximum length should pass."""
        assert validate_string_length("12345", max_length=5)

    def test_empty_string_with_no_constraints_passes(self):
        """Empty string with no constraints should pass."""
        assert validate_string_length("")

    @given(text=st.text(min_size=1))
    def test_empty_string_with_minimum_fails(self, text):
        """Empty string with minimum constraint should fail."""
        assert not validate_string_length("", min_length=1)
